Repository oscal-compass/compliance-trestle, pull requests merged in 2021-05, with the labels that each got.

#518 chore: CICD improvements
  .github/workflows/conventional-pr.yml
  .github/workflows/python-push.yml
  .github/workflows/python-test.yml
  .github/workflows/trestle-develop-automerge.yml
  .github/workflows/trestle-main-automerge.yml
  README.md
  docs/index.md
Labels: auto-merge, pr-ready

#520 fix: Correct semantic / conventional commit behaviour
  .github/workflows/conventional-pr.yml
  .github/workflows/trestle-develop-automerge.yml
  .github/workflows/trestle-main-automerge.yml
Labels: auto-merge, pr-ready

#521 chore: Clean up PR automation
  .github/workflows/conventional-pr.yml
  .github/workflows/python-push.yml
  .github/workflows/python-test.yml
  .github/workflows/trestle-develop-automerge.yml
  .github/workflows/trestle-main-automerge.yml
Labels: auto-merge, pr-ready

#519 feat: create title - place names in title of created objects - issue #473
  tests/trestle/core/commands/create_test.py
  trestle/core/commands/create.py
Labels: Nonconventional, auto-merge, pr-ready

#522 fix: Ensure PR automation system cannot override checks.
  .github/workflows/python-test.yml
  .github/workflows/trestle-develop-automerge.yml
  .github/workflows/trestle-main-automerge.yml
Labels: auto-merge, automerge

#523 chore: Updated some docs to trigger a PR
  trestle/core/all_validator.py
Labels: automerge

#524 docs: Small set of document updates
  .github/workflows/trestle-develop-automerge.yml
  trestle/core/utils.py
Labels: automerge

#525 docs: Additional documentation.
  trestle/core/object_factory.py
Labels: automerge

#506 fix: stop split at strings, better handling of component-def splits
  tests/test_utils.py
  tests/trestle/conftest.py
  tests/trestle/core/base_model_test.py
  tests/trestle/core/commands/add_test.py
  tests/trestle/core/commands/cmd_utils_test.py
  tests/trestle/core/commands/init_test.py
  tests/trestle/core/commands/merge_test.py
  tests/trestle/core/commands/split_test.py
  tests/trestle/core/models/create_path_action_test.py
  tests/trestle/core/models/element_test.py
  tests/trestle/core/models/remove_path_action_test.py
  tests/trestle/core/parser_test.py
  tests/trestle/utils/fs_test.py
  trestle/core/base_model.py
  trestle/core/commands/add.py
  trestle/core/commands/import_.py
  trestle/core/commands/init.py
  trestle/core/commands/merge.py
  trestle/core/commands/remove.py
  trestle/core/commands/replicate.py
  trestle/core/commands/split.py
  trestle/core/models/actions.py
  trestle/core/models/elements.py
  trestle/core/utils.py
  trestle/utils/fs.py
  trestle/utils/load_distributed.py
  trestle/utils/trash.py
Labels: automerge

#526 docs: More google style doc strings
  trestle/core/ncname_validator.py
Labels: automerge

#531 docs: Reorg and cleanup content
  docs/api_overview.md
  docs/api_reference/trestle.core.oscal_version_validator.md
  docs/cli.md
  docs/errors.md
  docs/index.md
  docs/python_trestle_setup.md
  docs/reference/third-party-result-schema-SCC.md
  docs/trestle_md.md
  docs/tutorials/continuous-compliance/continuous-compliance.md
  docs/tutorials/trestle_sample_workflow.md
  docs/tutorials/tutorials.md
  mkdocs.yml
Labels: automerge

#538 fix: Remove problematic concurrency restrictions in devops pipeline
  .github/workflows/python-push.yml
Labels: automerge

#540 fix: Trigger release
  .github/workflows/python-push.yml
Labels: automerge

#542 fix: Improve devops to stop squash merging to main
  .github/workflows/trestle-develop-automerge.yml
Labels: automerge

#546 fix: move unreachable debug statement
  trestle/core/commands/split.py
Labels: automerge

#539 feat: Adding drawio metadata extraction capability
  tests/data/drawio/not_mxfile.drawio
  tests/data/drawio/single_tab_bad_metadata_extra_fields_compressed.drawio
  tests/data/drawio/single_tab_bad_metadata_missing_fields_compressed.drawio
  tests/data/drawio/single_tab_metadata_compressed.drawio
  tests/data/drawio/single_tab_no_metadata_compressed.drawio
  tests/data/drawio/single_tab_no_metadata_uncompressed.drawio
  tests/data/drawio/single_tab_no_metadata_uncompressed_mangled.drawio
  tests/data/drawio/two_tabs_metadata_compressed.drawio
  tests/data/drawio/two_tabs_metadata_second_tab_compressed.drawio
  tests/trestle/core/draw_io_test.py
  trestle/core/draw_io.py
Labels: automerge

#549 fix: errors in Split for roles and compdefs (lists and dicts)
  tests/trestle/core/commands/split_test.py
  trestle/core/models/elements.py
Labels: automerge

#552 fix: CICD cleanup to prevent admin
  .github/workflows/trestle-develop-automerge.yml
Labels: automerge
